- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: 
    update_cache: yes 
    name: docker-ce 
    state: latest

- name: Install Docker Module for Python
  pip:
    name: docker


- name: Ensure jenkins directory on docker host
  file:
    state: directory
    owner: "1000"
    group: "1000"
    path: /share/jenkins


- name: Pull the latest official jenkins docker image
  docker_image:
    name: "sonarqube"
    source: pull